// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvQYZvnYtrfa43wQSRgF6Fehblf_xzvos',
    appId: '1:1040514666061:web:f1dcdc50986f84c8145604',
    messagingSenderId: '1040514666061',
    projectId: 'movie-browsing-app',
    authDomain: 'movie-browsing-app.firebaseapp.com',
    storageBucket: 'movie-browsing-app.firebasestorage.app',
    measurementId: 'G-824WY9W1JY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnrMOPBSags4rTteYyQaEwLlUias5lsDM',
    appId: '1:1040514666061:android:fb89209c7d2699d9145604',
    messagingSenderId: '1040514666061',
    projectId: 'movie-browsing-app',
    storageBucket: 'movie-browsing-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMP1G1lbrZ8oZ4MDUJ3tUX_rsZwOmko0M',
    appId: '1:1040514666061:ios:d70d89a3267c6025145604',
    messagingSenderId: '1040514666061',
    projectId: 'movie-browsing-app',
    storageBucket: 'movie-browsing-app.firebasestorage.app',
    iosBundleId: 'com.example.movieBrowsingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMP1G1lbrZ8oZ4MDUJ3tUX_rsZwOmko0M',
    appId: '1:1040514666061:ios:d70d89a3267c6025145604',
    messagingSenderId: '1040514666061',
    projectId: 'movie-browsing-app',
    storageBucket: 'movie-browsing-app.firebasestorage.app',
    iosBundleId: 'com.example.movieBrowsingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvQYZvnYtrfa43wQSRgF6Fehblf_xzvos',
    appId: '1:1040514666061:web:448452f3de2d255c145604',
    messagingSenderId: '1040514666061',
    projectId: 'movie-browsing-app',
    authDomain: 'movie-browsing-app.firebaseapp.com',
    storageBucket: 'movie-browsing-app.firebasestorage.app',
    measurementId: 'G-SDDZ84V522',
  );

}