// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDZv1Amf7BbZ47FVllZSoj5EY9nGSvmZI',
    appId: '1:473487710445:web:c2a491726ee9daa1df94e4',
    messagingSenderId: '473487710445',
    projectId: 'slop-movie-app-2025',
    authDomain: 'slop-movie-app-2025.firebaseapp.com',
    storageBucket: 'slop-movie-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR8OCicW1ddedgymVFgqDG3JD5hIeUx4A',
    appId: '1:473487710445:android:c2c913e8898c4ff2df94e4',
    messagingSenderId: '473487710445',
    projectId: 'slop-movie-app-2025',
    storageBucket: 'slop-movie-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5qN8uN6PoCH_2psn4GUwuxyHQNQGbQIE',
    appId: '1:473487710445:ios:3c96d1f0031c3205df94e4',
    messagingSenderId: '473487710445',
    projectId: 'slop-movie-app-2025',
    storageBucket: 'slop-movie-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.movieBrowsingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5qN8uN6PoCH_2psn4GUwuxyHQNQGbQIE',
    appId: '1:473487710445:ios:3c96d1f0031c3205df94e4',
    messagingSenderId: '473487710445',
    projectId: 'slop-movie-app-2025',
    storageBucket: 'slop-movie-app-2025.firebasestorage.app',
    iosBundleId: 'com.example.movieBrowsingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDZv1Amf7BbZ47FVllZSoj5EY9nGSvmZI',
    appId: '1:473487710445:web:c455785917153e3bdf94e4',
    messagingSenderId: '473487710445',
    projectId: 'slop-movie-app-2025',
    authDomain: 'slop-movie-app-2025.firebaseapp.com',
    storageBucket: 'slop-movie-app-2025.firebasestorage.app',
  );
}
